spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/delibuddy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 22380476
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    database: mysql
    properties:
      hibernate.dialect: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect

logging:
  level:
   org:
    hibernate:
      SQL: debug
      type: trace

api:
  v1: /api/v1

