spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delibuddy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 22380476
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
