# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, sw-github-action-test ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: delibuddy
      DB_USER: root
      DB_PASSWORD: 22380476

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Start Mysql
      # https://ovirium.com/blog/how-to-make-mysql-work-in-your-github-actions/
      - name: Start Mysql
        run: |
          sudo systemctl start mysql
          mysql -e "use mysql; FLUSH PRIVILEGES; ALTER USER 'root'@'localhost' IDENTIFIED BY '22380476';" -u${{ env.DB_USER }} -proot
          mysql -e 'CREATE DATABASE delibuddy;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      # Set up JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3

      # Gradle build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: cat log
        if: ${{ always() }}
        run: cat /home/runner/work/Android-Team-1-Backend/Android-Team-1-Backend/build/reports/tests/test/classes/com.example.delibuddy.domain.user.UserRepositoryTest.html
